### PR TITLE
change force print no2

### PR DESCRIPTION
**Pull request by ayamada224**
A tiny bug for recent force printing in xxx_trj.xyz was fixed. (bug at initial step)

I added an additional output data at 21th column in xxxx_rt.data: Work energy for ion which is obtained by integrating force*dRion to get useful energy without messed energetic egg box effect for MD option.

### CODE REVIEW

**Comment by uemoto1** [comment]
Thank you @ayamada224 san. I will check it later.

**Review by uemoto1 — COMMENTED** [review]
Thank you for developing @ayamada224 san.
I have checked this PR and found a problem happens in the restarting of the multiscale calculation. For the reproduction, I attach the example input file as below:
https://gist.github.com/uemoto1/3787729324395da2b09dcc568aa37ccc

**Comment by uemoto1** [comment]
The computation is performed in the Oakforest PACS  with the number of MPI nodes = 2.

```
forrtl: severe (154): array index out of bounds
Image              PC                Routine            Line        Source             
salmon.mic         000000000076524E  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B19770C1100  Unknown               Unknown  Unknown
salmon.mic         00000000004E55A3  Unknown               Unknown  Unknown
libiomp5.so        00002B19750CD7A3  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002B197509B9C7  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002B1975064ABC  __kmpc_fork_call      Unknown  Unknown
salmon.mic         00000000004E2A6E  Unknown               Unknown  Unknown
salmon.mic         000000000041C4ED  Unknown               Unknown  Unknown
salmon.mic         0000000000406445  Unknown               Unknown  Unknown
salmon.mic         00000000004062FB  Unknown               Unknown  Unknown
salmon.mic         0000000000405FDE  Unknown               Unknown  Unknown
libc-2.17.so       00002B19775F1B15  __libc_start_main     Unknown  Unknown
salmon.mic         0000000000405EE9  Unknown               Unknown  Unknown
forrtl: severe (154): array index out of bounds
Image              PC                Routine            Line        Source             
salmon.mic         000000000076524E  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B126CD9C100  Unknown               Unknown  Unknown
salmon.mic         00000000004E55A3  Unknown               Unknown  Unknown
libiomp5.so        00002B126ADA87A3  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002B126AD769C7  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002B126AD3FABC  __kmpc_fork_call      Unknown  Unknown
salmon.mic         00000000004E2A6E  Unknown               Unknown  Unknown
salmon.mic         000000000041C4ED  Unknown               Unknown  Unknown
salmon.mic         0000000000406445  Unknown               Unknown  Unknown
salmon.mic         00000000004062FB  Unknown               Unknown  Unknown
salmon.mic         0000000000405FDE  Unknown               Unknown  Unknown
libc-2.17.so       00002B126D2CCB15  __libc_start_main     Unknown  Unknown
salmon.mic         0000000000405EE9  Unknown               Unknown  Unknown
```

**Comment by ayamada224** [comment]
I fixed the restarting of multi-scale calculations: The reason was that the recent change of adding "BACKUP(Vpsl_ia)" had not merged. 

I also added new force-printing keywords (out_rvf_rt / out_rvf_rt_step) in the manual.

**Comment by uemoto1** [comment]
Thank you @ayamada224 san for debugging.
I will continue reviewing!

**Comment by uemoto1** [comment]
I confirm this pull request works well! Thank you for contribution, @ayamada224 san!

**Pull request merged**
