### PR TITLE
Cube file of different density (xxx_dns_dlt_00XX.cube) is modified for my option (ARTED side)

### PR DESCRIPTION
**Pull request by ayamada224**
Cube file of different density between excited and ground states (file name: xxx_dns_dlt_00yyy.cube) was modified for MD option due to changes of ion coordinates. Then, following parts were changed:

(1) writing part for cube option in RT main routine
The writing part for cube option were moved from the main RT routine into new subroutine "write_density" in density_plot.f90 file. (to simplify the main RT routine... main RT routine has lots of writing parts...) 

(2) k_shift_wf subroutine
subroutines, k_shift_wf and k_shift_wf_last, were unified because the functions were very similar and overlapped. Then, now k_shift_wf is for analysis which needs GS state iteration at time t in the cases like projection option. Now new option to generate GS density at time t was implemented for cube file in MD option. The GS iteration process in the new k_shift_wf subroutine was improved to be more accurate convergence even though it takes a little longer time. (subroutine name k_shift_wf should be changed to be better for easy understanding)

(3) xxx_dns_dlt_00yyy.cube file for MD option
Just an if sentence of md option was inserted, where GS density with updated ion coordinates at time t is used for different density.

Atsushi Yamada

### CODE REVIEW

**Comment by uemoto1** [comment]
Thank you @ayamada224 san, I will check this PR.

**Review by uemoto1 — CHANGES_REQUESTED** [review]
Thank you @ayamada224 san. Can you modify `src/ARTED/contol/control_ms.f90:290` for appropriate to the the present implementation of `k_shift_wf`?

**Comment by ayamada224** [comment]
I fixed k_shift_wf in control_ms.f90

**Comment by uemoto1** [comment]
Thank you @ayamada224 san. Currently I have a problem in the multiscale calculation as below:
https://gist.github.com/uemoto1/367c0a56211d4be06447ea40ef0ee906
I have been trying to find out the origin of the segmentation fault, and I think I need a little more time.
Sorry for inconvenience...

**Review by uemoto1 — APPROVED** [review]

**Comment by uemoto1** [comment]
Thank you @ayamada224 san, I confirmed the modified code successfully reproduces the previous results. I think this PR is available to merge into the developer branch. (I will merge after the automatic test finished.)

**Pull request merged**
