### PR TITLE
modify a relationship between trans_longi and iflag_indA

### PR DESCRIPTION
**Pull request by mn2007**
In the GCEED part, a relationship between trans_longi and iflag_indA was wrong. So I modify it. @tt-ims san, could you check?

### CODE REVIEW

**Comment by uemoto1** [comment]
test this please

**Comment by mn2007** [comment]
It seems that checks have passed. Thank you, @uemoto1 san.

**Comment by tt-ims** [comment]
I approve this PR.

**Comment by mn2007** [comment]
Thank you for merging, @tt-ims san.

**Pull request merged**
