### PR TITLE
Change version number to 1.1.0

### PR DESCRIPTION
**Pull request by uemoto1**
## Congratulations! 
logo_fish
This PR will be the final change before release of SALMON-v.1.1.0 !

```
##############################################################################
# SALMON: Scalable Ab-initio Light-Matter simulator for Optics and Nanoscience
#
#                             Version 1.1.0
```

- Change the version number printed out in the stdout
- Add macro variables `SALMON_VER_(MAJOR|MINOR|MICRO)` to set the version number in `src/version.h.in`

### CODE REVIEW

**Comment by mn2007** [comment]
Now I'm checking whether gnumake successfully finishes. Could you wait for a while, @uemoto1 san? Thank you for your patience.

**Comment by mn2007** [comment]
I confirmed that gnumake successfully finished on FX machine. Congraturations! I approve this PR. @yabana sensei, could you comment on this PR?

**Review by mn2007 — COMMENTED** [review]
I approve this PR.

**Comment by mn2007** [comment]
@ayamada224 san reported that out of array access occurs when broyden method is used at final iteration for scf calculations. So I'll modify the code soon.

**Comment by mn2007** [comment]
Now the problem was solved in PR #318. Is it possible to merge?

**Comment by uemoto1** [comment]
@mn2007 san, I guess it seems to be possible. 
@yabana, After merging this PR, is it okay to release v.1.1.0?

**Comment by mn2007** [comment]
Thank you for the comment, @uemoto1 san. I merge this PR.

**Pull request merged**
