### PR TITLE
modify testsuites

### PR DESCRIPTION
**Pull request by mn2007**
I modify testsuites in order that the checks pass in gpu environment.

### CODE REVIEW

**Comment by mn2007** [comment]
Lines to be checked are displaced from correct ones. So I modified.

**Comment by mn2007** [comment]
I modified a line to be checked for a pulse calculation.

**Comment by mn2007** [comment]
Somehow the way of line count was different, so I modified.

**Comment by mn2007** [comment]
I finished modification. @uemoto1 san, could you merge?

**Comment by uemoto1** [comment]
Thank you @mn2007 san to fix the testsuites, and I guess it works well.

**Comment by mn2007** [comment]
Thank you for merging, @uemoto1 san.

**Pull request merged**
