### PR TITLE
modify dos and pdos

### PR DESCRIPTION
**Pull request by mn2007**
Thank you for your implementation, @uemoto1 san. And thank you for your advice, @shunsuke-sato san. But I found that top and bottom dos are cut when I use lorentzian function for C2H2 case. This is what @yabana sensei said. I'd like to modify the code as following. 

1. I enlarge energy ranges for the DOS and PDOS plot. 
2. Since out_dos_start and out_dos_end in std input is no longer used, I remove them. But they remain as SALMON global variables.
3. According to the coding rules, I modify from out_dos_nenergy to iout_dos_nenergy. 

People who check may disagree above modification. In that case, I'll modify. So please do not hesitate to comment on this PR.

### CODE REVIEW

**Comment by mn2007** [comment]
I forgot to say one thing. I tested for the ARTED part and the GCEED part as much as I consider.

**Comment by uemoto1** [comment]
Thank you for contribution, @mn2007 san.

I understand your point and agree to use `iout_dos_nenergy` to obey of the coding rules.   This PR also modified estimation method which provides the much wider range than all electron eigenenergies. I agree it is better than the previous one to understand the entire DoS structure from one plotted graph.
On the other hand, I guess there is a merit to specify the upper and lower bound for usabilities. 

Therefore, I have an idea to add the lines below:
```
if (out_dos_start <= 1.d+10) out_dos_start = ene_min-0.25d0*(ene_max-ene_min)
if (out_dos_end >= 1.d+10) out_dos_end = ene_max+0.25d0*(ene_max-ene_min)
```
or
```
out_dos_start = max(out_dos_start, ene_min-0.25d0*(ene_max-ene_min))
out_dos_end = min(out_dos_end, ene_max+0.25d0*(ene_max-ene_min))
```
.
 
I prefer using the implementation above. it makes possible to coexist both of  @mn2007 san's method and previous range specification in the same code.

I think this PR is mainly available to merge. 
If you need immediate merging, please told it to me.

**Comment by mn2007** [comment]
Thank you for your comment, @uemoto1 san. I would like to implement latter one you suggested. So could you wait until I implement?

**Comment by uemoto1** [comment]
Thank you for consideration, I will looking forward the next upload.

**Comment by mn2007** [comment]
I finished the implementation. I checked with setting and not setting out_dos_start and out_dos_end for both the ARTED part and the GCEED part, and I obtained results which are satisfied.

**Comment by mn2007** [comment]
If @uemoto1 san judges that it's acceptable to merge, could you merge this PR immediately? Thanks in advance.

**Comment by uemoto1** [comment]
Thank you @mn2007 for modification.
I have checked the DoS calculation in ARTED part works well, and it is available to merge to develop branch.

**Pull request merged**
