### PR TITLE
Implemented unit-converter for input

### PR DESCRIPTION
**Pull request by shunsuke-sato**
**Please merge This PR!**

To employ common input for both ARTED and GCEED parts, I implemented the unit converter for the input variables. Now, units can be chosen by the namelist `&units`:
For time `unit_time`, the atomic unit (`au` and `a.u.`) and the femtosecond (`fs` and `femtosecond`) can be chosen.
For length `unit_length`, the atomic unit, and the Angstrom  (`AA`, `Angstrom`,and `angstrom`) can be chosen.
For energy `unit_energy`, the atomic unit and the electron-volt (`eV` and `ev`) can be chosen.
For charge `unit_charge`, the atomic unit is only available.

For all the unit, the atomic unit is default at the moment.

### CODE REVIEW

**Comment by shunsuke-sato** [comment]
@uemoto1 san, thank you for fixing the conflict!

**Comment by shunsuke-sato** [comment]
@uemoto1 san, @mn2007  san, I would like to ask both of you to review this PR since this affects both ARTED and GCEED parts. So, could you merge this after both approving it, please?
Also, if there is a problem, could you send me a comment or directly fix and push to this branch?
Thank you for your help in advance.

**Comment by uemoto1** [comment]
Thanks, I confirmed how this PR works, and possible to merge from view point of the ARTED part...

**Review by uemoto1 — APPROVED** [review]

**Comment by mn2007** [comment]
I also checked this PR and it looks so nice. I merge this PR. Thank you for your work.

**Comment by shunsuke-sato** [comment]
@uemoto1 san and @mn2007 san, thank you very much for your quick review and merge.

**Pull request merged**
