### PR TITLE
create testsuite 

### PR DESCRIPTION
**Pull request by mn2007**
I add testsuite for some calculations of isolated systems in the first stage. I'm not sure how to check correctness of the testsuite. @uemoto1 san, could you tell me whether it works or not when you have a time? If it doesn't work, I'll consider other solutions.

### CODE REVIEW

**Comment by mn2007** [comment]
I was not supposed that the build fails. @uemoto1 san, is it easy for you to solve this problem? Maybe this isn't an urgent task.

**Review by uemoto1 — COMMENTED** [review]
Thank you @mn2007 for developing.
According to the error message, the tester failed to copy the pseudo potential files as below:
https://diana.ccs.tsukuba.ac.jp/jenkins/job/SALMON_PULL_REQUEST/294/console

Could you add `C_rps.dat` and `H_rps.dat` into the  `SALMON/testsuites/pseudo/` directory?

**Comment by mn2007** [comment]
Thank you for your advice, @uemoto1 san. I added files by a command `git add -f`. I'll see what happens.

**Comment by mn2007** [comment]
I'm so surprised that all checks passed. @uemoto1 san, does jenkins check test 101 and 102 at the moment?

**Comment by uemoto1** [comment]
Thank you for report @mn2007 .

I'm checking this problem. 
At least, verification scripts returns `success` flags.
It is very strange behavior, I will check it, please wait a moment...

```
Regression Test: 101_C2H2_gs
./preparation: line 11: [: missing `]'
############################################################
# Verification start
# Checking the existance of outputfile
# Verification end
############################################################
Regression Test: 102_C2H2_rt_response
############################################################
# Verification start
# Checking the existance of outputfile
# Verification end
############################################################
```

**Review by uemoto1 — APPROVED** [review]
@mn2007 san, I think at present commitment, this testsuites works well both in CMake test and Jenkins.

**Comment by mn2007** [comment]
If possible, I have a plan to give another PR tomorrow which makes run a pulse calculation and checks calculated values. Could you merge this PR, @uemoto1 san?

**Comment by uemoto1** [comment]
Okey. I will merge this.

**Comment by mn2007** [comment]
Thank you for merging, @uemoto1 san.

**Pull request merged**
