### PR TITLE
Implemented unit conversion for output.

### PR DESCRIPTION
**Pull request by shunsuke-sato**
- I added a header for the current-density file and implemented the unit conversion for the current. 

- I would say that this implementation is not the best solution, but a compromise between readability of output and convenience for maintenance/extension of the code.
If anyone has a good idea, please let us know. Otherwise, I'll continue to work based on this implementation.

### CODE REVIEW

**Comment by mn2007** [comment]
Thank you for your implemetentation. I might use this kind of modification for polarizability or something. Could you continue to implement?

**Comment by shunsuke-sato** [comment]
Thank you for your comment. Here, I tried to prepare the unit-conversion variables at beginning of the calculation, and to avoid computing on the fly in order to avoid the following situation: developers have to revisit all over the codes when the unit part is modified.

OK! I'll continue to work! But, could you merge this PR so that other developers could kindly participate the output-file modification.

**Comment by mn2007** [comment]
I'd like to merge if I can. But the modification affects to the ARTED part. So, I'd like to wait other people comment. Sorry for that.

**Review by uemoto1 — APPROVED** [review]
Thanks Sato-san, Okey, I confirm this PR.

**Pull request merged**
