### PR TITLE
add classic em.

### PR DESCRIPTION
**Pull request by tt-ims**
This pull request adds classical EM calculation. The attachment is input and output data. Please use it as a reference.
[inp_and_data.zip](https://github.com/SALMON-TDDFT/SALMON/files/2481481/inp_and_data.zip)

### CODE REVIEW

**Comment by tt-ims** [comment]
Explanations for new input variables will be added to SALMON-DOCS, soon.

**Comment by tt-ims** [comment]
Sorry, previous input file is incorrect. I will upload modified one. 
[inp_and_data_mod.zip](https://github.com/SALMON-TDDFT/SALMON/files/2482139/inp_and_data_mod.zip)

**Comment by tt-ims** [comment]
@uemoto1 san and @yhirokawa san, Thank you so much for fixing the problem!

**Comment by mn2007** [comment]
Calculated results on FX100 with 8 processors are completely same as the one provided by @tt-ims san. So I approve this PR.

**Review by mn2007 — APPROVED** [review]
I approve this PR.

**Comment by mn2007** [comment]
@tt-ims san seemed to mistake the operation ... .

**Comment by tt-ims** [comment]
Sorry, @shunsuke-sato san and @syamada0 san. I mistook to choose...
@mn2007 san, thank you for indicating it.

**Review by syamada0 — APPROVED** [review]

**Review by uemoto1 — APPROVED** [review]
I confirm this pull request works. Thank you for contribution1 @tt-ims san!

**Comment by tt-ims** [comment]
@mn2007 san, @syamada0 san, and @uemoto1 san, thank you for approving and merging!

**Pull request merged**
