### PR TITLE
Optimizing halo communications in GCEED part.

### PR DESCRIPTION
**Pull request by yhirokawa-ccs**
I optimized halo communications (peer-to-peer communications) in GCEED part as follows:

1. optimize pack/unpack routines.
2. use persistent communication of MPI.

I checked the performance results under Xeon Phi 16 nodes, this PR reduced 20% of total execution time when RT calculation.

## Verification of results

I verified calculation results with C2H2 molecule example under Xeon Phi as following process distributions:

1. Xeon Phi executes with 16 MPI processes
2. `nproc_ob` sets `2`.
3. `nproc_domain` sets `2,2,2`
4. `nproc_domain_s` sets `4,2,2`

## Note

I will send PR for reducing and unifying halo communications after merged it.

## Suggestion
`C_sendrecvh` and `sendrecv_groupob_ngp` are never used, so I suggest that remove it.

### CODE REVIEW

**Comment by mn2007** [comment]
Thank you for your implementation, @yhirokawa san. I'll take a benchmark and reply this PR later, and I'll consider your suggestion.

**Comment by mn2007** [comment]
I confirmed that the implemented code is 1.34 times faster than before. It's too amazing for me. I'd like to pass this PR, but one problem is left. Fujitsu compiler doesn't pass the build for this code. I'll specify the point by a review function.

**Review by mn2007 — CHANGES_REQUESTED** [review]
In src/GCEED/common/sendrecv_copy.f90, could you move two private(iz, iy, ix) sentences from inside an iob loop to outside the iob loop? In other word, could you write private(iob, iz, iy, ix) before the iob loop?

**Comment by yhirokawa-ccs** [comment]
@mn2007 san, thank you for reviewing. I fixed omp directives in sendrecv_copy.f90.

**Review by mn2007 — APPROVED** [review]
I approve this PR.

**Comment by mn2007** [comment]
Thank you for the modification and the large contribution, @yhirokawa san. I merge this PR.

**Pull request merged**
