### PR TITLE
modify header

### PR DESCRIPTION
**Pull request by mn2007**
I modify header of C2H2_lr.data and C2H2_ps.data by following Prof. Yabana's suggestion. @tt-ims san, could you check this PR?

### CODE REVIEW

**Comment by tt-ims** [comment]
@mn2007 san
I will check your pull request.

**Comment by mn2007** [comment]
I found that line break is inserted in headers when I run the calculation on intel machine. I'll modify.

**Comment by mn2007** [comment]
I finished modification. Could you check after all checks pass, @tt-ims san?

**Comment by tt-ims** [comment]
@mn2007 san
I will check your pull request.

**Comment by tt-ims** [comment]
@mn2007 san
I checked your pull request. Confirmed that header is generated correctly. There is no problem to merge this pull request.

**Comment by mn2007** [comment]
Thank you for checking and merging, @tt-ims san.

**Pull request merged**
