### PR TITLE
modify copyright in GCEED part

### PR DESCRIPTION
**Pull request by mn2007**
I modify copyright in GCEED part. (name of each developer -> SALMON developers)

### CODE REVIEW

**Comment by uemoto1** [comment]
Thank you! I confirm this PR is okey to merge. (But take care to some confliction..)

**Comment by shunsuke-sato** [comment]
@mn2007 san, and @uemoto1 san, I think no one complains this PR, and we do not need to wait for responses of other developers. So, could you fix this conflict and merge this PR to avoid further conflicts?

**Comment by mn2007** [comment]
I resolved the conflicts but I'm not sure that person who should resolve the conflicts is the one who gave PR.   If my action was wrong, please tell me.

**Comment by shunsuke-sato** [comment]
@mn2007 san, thank you for fixing the problem. Now, I could not manage time to see the code, but I'll review and merge it later, if anyone do not so at that time.
I personally think that owner of PR should fix conflicts if it is trivial since it is the easiest solution. But, I know it can be annoying... Quick review & merge would be only the solution to keep the developing environment comfortable...

**Comment by mn2007** [comment]
I understand that it depends on cases. Thank you for your comment, @shunsuke-sato san.

**Pull request merged**
