### PR TITLE
Add the charge density output to cube and vtk file

### PR DESCRIPTION
**Pull request by uemoto1**
This pull request provides the charge density output to the gaussian cube file and VTK file, when the `out_dns` or `out_dns_rt` switch equals `y`.

### CODE REVIEW

**Comment by mn2007** [comment]
Please let me give a comment. In my memory, format is very important for cube files. The format of header is i5,3f12.6 or i5,4f12.6. And 3d data forms six rows. Have you checked whether cube files are correctly displayed? If so, I'll merge this PR.

**Comment by mn2007** [comment]
Or if you implement same format as GCEED/common/writecube.f90, I can approve this PR.

**Comment by uemoto1** [comment]
Thx for reviewing, @mn2007 san, i will check the related part.

**Comment by mn2007** [comment]
I add this PR to whitelist

**Pull request merged**
