### PR TITLE
Wrapped all communication routines in GCEED part.

### PR DESCRIPTION
**Pull request by yhirokawa-ccs**
I wrapped all communication routines in GCEED part.

I verified the calculation results with C2H2 molecule samples (sample 1-3), but this PR may exists any bugs because this is a big modification.
Would you please check the calculation results under GCEED part?

### CODE REVIEW

**Comment by mn2007** [comment]
I understand. I'll try to do tests under some conditions. 
Maybe I'll make a responce to this tomorrow morning.

**Comment by mn2007** [comment]
I'm trying to check and I found that it may take time to implement this PR. 
Sorry for that and I appreciate your contribution.

First comment is about deadlock. What I did was to check GS calculation with FX10 12 nodes modifying the input from 
<pre>
  nproc_domain = 1,1,1
  nproc_domain_s = 1,1,1
</pre>
to
<pre>
  nproc_domain = 3,4,1
  nproc_domain_s = 3,4,1
</pre>
As a result, the calculation stopped because of dead lock of communication. A part where the calculation stopped was around line 250 in GCEED/common/hartree_boundary.f90. GCEED used variable "nproc" as the number of total processors, not as rank. So, when total number of processors is 1, copy of array is done in that part, and when the total number of processors is larger than 1, allreduce is done. 

I guess that easiest way to solve the problem is to replace from "nproc_id_global==1" to "nproc_size_global=1". Using the grep command, I found that there are 6 parts where it is written "nproc_id_global==1". Could you apply this modification at first?

**Comment by yhirokawa-ccs** [comment]
@mn2007 san, thank you for reporting! I solved a deadlock with your suggestion, but some bugs still exist. Maybe I will send a bugfix commit to next week.

**Comment by mn2007** [comment]
@yhirokawa san, thank you for your reply. It's really tough work for me, so I prefer to do this kind of work next week.

**Comment by yhirokawa-ccs** [comment]
I sent a pull request #76 for solving bugs. Would you please check and merge it?

**Comment by mn2007** [comment]
As I mentioned PR#76, I merged it. Thank you.

**Comment by yhirokawa-ccs** [comment]
@mn2007 san, thank you for merging. I rebased it because Sato-san fixed freeze bug in GCEED part.
I verified the results under knights landing 16 nodes.

    nproc_domain = 4,2,2
    nproc_domain_s = 4,2,2

Would you please check the results?. But there is not rush, so please take your time.

**Comment by mn2007** [comment]
I understand. I'll do some tests on Monday. Although I didn't tell you that there was parts that a process sending data in bcast is not rank 0, you dealed with that. I really appreciate your efforts.

**Comment by mn2007** [comment]
All I have to do is to figure out why ground state calculation stops at the end when following condition is specified for the calculation using FX10 12node. 
<pre>
  nproc_ob=2
  nproc_domain = 3,2,1
  nproc_domain_s = 3,4,1
</pre>
All other checks have passed. After I figure out the reason, I'll inform you.

**Comment by mn2007** [comment]
The calculation stops even if I use other branch, so it's my fault. Could you wait until I figure out the reason. Thank you for your patience.

**Comment by mn2007** [comment]
Since it's my fault, I'll give another PR that fix this problem. I merge this PR.

**Review by mn2007 — APPROVED** [review]
I approve this PR.

**Pull request merged**
