### PR TITLE
Enabled to use odd numbers of real-space grid points.

### PR DESCRIPTION
**Pull request by shunsuke-sato**
Number of grid points is not necessary to be an even number. Thus, I enabled to use odd numbers of grid points in ARTED part.

### CODE REVIEW

**Comment by mn2007** [comment]
I tried with modifying sc sample to num_rgrid = 13, 13, 13 but calculation stops displaying "Bad grid point". I can not figure out this can be merged. Other people may merge this PR.

**Review by uemoto1 — CHANGES_REQUESTED** [review]
Thank you for developing and reviewing, @shunsuke-sato and @mn2007 

I also detected a same error message. And, I guess this problem is caused by the following part in `initialization.f90`:

```
ARTED/control/initialization.f90:188:if((mod(NLx,2)+mod(NLy,2)+mod(NLz,4)) /= 0)call err_finalize('Bad grid point')
ARTED/control/initialization.f90:201:if((mod(NLx,4)+mod(NLy,4)+mod(NLz,4)) /= 0)call err_finalize('Bad grid point')
ARTED/control/initialization.f90:215:if((mod(NLx,4)+mod(NLy,4)+mod(NLz,4)) /= 0)call err_finalize('Bad grid point')
```

After commenting out the lines above, the calculation of n=13 crystal works and reproduce the similar result of the n=12 case.

**Comment by shunsuke-sato** [comment]
@mn2007 san and @uemoto1 san, thank you for reviewing. I guess both of you used wrong symmetry for the test... 
Because of the grid representation, a crystal symmetry can be broken. So, I guess, in your calculations, SALMON detected the symmetry breakdown and stopped.
So, I would advise you not to use the symmetry function unless it is clear to you.

**Comment by mn2007** [comment]
Thank you for your comment, @shunsuke-sato san. But I guess most users simply change num_rgrid and would not understand what is wrong. So I'm glad if you add recommended variables in stop sentence when users use wrong variables. If you disagree, I check with changing the variable isym and may merge this PR.

**Comment by uemoto1** [comment]
Thank you @shunsuke-sato san, I will re-check it later.

**Comment by shunsuke-sato** [comment]
@mn2007 san, yes, the present error message is not helpful for users. I will modify it in the future.

But, I do not suppose users use this symmetry function because the symmetry function is too tricky, and thus, I do not think that we would provide this function to users in the forthcoming release: the present symmetry function requires specific crystal symmetries, specific atomic coordinates, and a specific laser polarization direction. Furthermore, the number of grid points should be carefully chosen not to break the expected crystal symmetry.
Therefore, I advised you not to use the symmetry function unless it is clear to you.

Also, I would like to emphasize that I provided input files in `ARTED/data/` not for users but for a quick regression test. So, I do not suppose that users use these input files with some modifications.

**Review by uemoto1 — APPROVED** [review]

**Comment by mn2007** [comment]
Thank you for your explanation, @shunsuke-sato san. I understand the situation. Therefore, I tried with using default values for "isym" and "crystal_structure". The calculation successfully finishes when num_rgrid = 12, 12, 12, but it stops at the begenning of RT calculation with ommiting error message "core dumped" when num_rgrid = 13, 13, 13. I may give up the review and if @uemoto1 san agrees to merge, there is no problem to be merged.

**Comment by uemoto1** [comment]
Thank you for @shunsuke-sato and @mn2007.

I have confirmed `num_rgrid = 13,13,13` calculation successfully works when the crystal symmetry is fixed to `isym=1` case.
I agree that the implementation of symmetry transforms with odd -number grid will become the complicated modification. For now, the target is limited for the non-symmetric calculation, but it is worth of merging to the develop branch.

When create the documentation of next version, I prefer to add the description; the odd-number grid is allowed only in the case of non-symmetric crystal for future.

**Comment by mn2007** [comment]
Then, I merge this PR. Thank you, @uemoto1 san and @shunsuke-sato san.

**Pull request merged**
