### PR TITLE
modify the definition of the time delay

### PR DESCRIPTION
**Pull request by mn2007**
I modify the definition of the time delay in the GCEED part based on PR#172. I'd like to ask @shunsuke-sato san to merge this PR if this modification is correct.

### CODE REVIEW

**Comment by shunsuke-sato** [comment]
@mn2007 san, thank you for implementation. But, it seems to be incorrect.
The pulse duration is defined not in `calc_env_trigon` but in `calcVbox`. Thus, the condition in `calcVbox` should be properly modified to shift the pulse in time.

**Comment by mn2007** [comment]
@shunsuke-sato san, thank a lot for your review. I'll consider your point, and maybe reply on today's evening.

**Comment by mn2007** [comment]
I also modify the pulse duration in calcVbox.f90. @shunsuke-sato san, could you check?

**Comment by shunsuke-sato** [comment]
@mn2007 san, thank you for fixing the code. I reviewed it and it looks fine. So, I merge it.

**Comment by mn2007** [comment]
@shunsuke-sato san, thank you for merging.

**Pull request merged**
