### PR TITLE
Add automatic test template

### PR DESCRIPTION
**Pull request by uemoto1**
## About This Pull Request
This PR provides the template files of the regression tests, which are automatically executed for the every pull requests on GitHub (`salmon-tddft/SALMON`). In this time, the directory `/testsuites/` is added for the test files.

## How the regression test works
This PR contains a simple template `/testsuites/001_bulk_gs/` as below:
- `001_bulk_gs_rt`: a directory of test calculation for silicon, and this directory contains:
    - `preparation`: a script file which is automatically executed before the test. If necessary, this script can be utilized for the preparation of the input data for following calculations.
    - `inputfile`: an input file used by the SALMON, the result of the calculation are exported as the `outputfile` in the same directory. For shortening the test time, the input file must be designed to consume the fewer computation resources.
    - `verification`: a script file which is automatically executed after the test. If necessary, this script can be utilized for the verification of the calculation result.

Every single test calculation must have its directory, and it must be named as `INDEX_TITLE`
In the testing sequence, the test cases in `/testsuites/INDEX_TITLE` are performed in ascending order of the index. In each single test case, the Jenkins execute the program as below:
1. `./preparation`
2. `$SALMON < ./inputfile > ./outputfile` (with using MPI)
3. `./verification`

The `verification` script MUST return code 0 (`exit 0`) if the calculation is successful. If a negative value is returned, the result is treated as a test failure.

## How to control the regression test by PR
The developer can control the mode of the regression test by adding the single line (`testmode=`) into the description of the pull requests.

### Execute all regression tests
```
testmode=all
```
- In this mode, all test cases are automatically performed. 
Although it is the most rigorous test, it is necessary to wait for a long time to get the results (as the number of test cases increased). 

### Execute the specific test
```
testmode=1,2,3
```
-  In this mode, the developer can specify the required test cases. If the  Influence range of code modification is limited, the execution only for the relevant calculations saves the time to wait.

### Skip the build and all tests
```
testmode=skip
```
- if the modification of the PR is limited to the documentation or comments (it does not affect the functionality of code), the `skip` mode is a reasonable choice.

- if `testmode` is not specified, only the building is performed.

## Command for Jenkins

testmode = all

### CODE REVIEW

**Comment by uemoto1** [comment]
test this please

**Comment by uemoto1** [comment]
The following is forcing test command for Jenkins. Please ignore it.

**Comment by uemoto1** [comment]
test this please

**Comment by yhirokawa-ccs** [comment]
I recommend as follows:

1. Rename directory: `/tools/testsuites` to `/testsuites` or `/tests`
    - In general, users expect that test suites exist top directory
1. `postprocess` renames to `verification`
    - Testers will be confused due to they think verification process is not contained to "postprocess".

**Comment by uemoto1** [comment]
Thank you @yhirokawa san. I understand your point. I will try to modify the configuration of Jenkins.

**Comment by uemoto1** [comment]
@yhirokawa san, I have changed some filenames in this pull request:
- Change `/tools/testsuites/` to `/testsuites/`
- Change `preprocess` to `preparation`
- Change `postprocess` to `verification`

And, now the test server is working in above new configulation.

P.S.
I will distribute the guest account of Jenkins server (https://diana.ccs.tsukuba.ac.jp/jenkins) by email later.

I also uploaded the job script of Jenkins as below:
https://gist.github.com/uemoto1/ec744e4b5e6f240c64801416a3e01b29

**Comment by yhirokawa-ccs** [comment]
@uemoto1 san, thank you for contributing. I think that automated testing framework works fine. I'll merge it.

**Comment by uemoto1** [comment]
Thank you @yhirokawa san, for decision and merging!

**Pull request merged**
