### PR TITLE
Add parallel and communication modules.

### PR DESCRIPTION
**Pull request by yhirokawa-ccs**
I added `salmon_parallel` and `salmon_communication` modules.
(ARTED/modules/communication.f90 will be removed in the near future)
This PR replaces MPI routine at main/* and modules/* files.

### CODE REVIEW

**Review by shunsuke-sato — APPROVED** [review]
@yhirokawa san, thank you for taking care of the communication. I have reviewed and approved it.

**Comment by mn2007** [comment]
I checked this branch with FX10 12 nodes and it correctly worked. Thank you.

**Review by mn2007 — APPROVED** [review]
I approve these changes.

**Comment by mn2007** [comment]
Should we wait all reviewers to approve?

**Review by uemoto1 — APPROVED** [review]

**Pull request merged**
