### PR TITLE
check a calculated result for a pulse

### PR DESCRIPTION
**Pull request by mn2007**
I prepare testsuite for a pulse calculation to check its result. @uemoto1 san, could you check again?

### CODE REVIEW

**Comment by mn2007** [comment]
Thank you for your suggestion. I'm not familiar with python, so your suggestion is helpful for me.

**Review by uemoto1 — APPROVED** [review]
Thank you @mn2007 san. I think your code does not have a significant problem and works well.
I have one recommendation: the loop on the line 38 in `verification` is meaningless and I suggest it is convenient to remove for the future upgrades of `checklist`.

**Comment by uemoto1** [comment]
I will merge this PR after finishing the present build test.

**Comment by mn2007** [comment]
Thank you for merging, @uemoto1 san.

**Pull request merged**
