### PR TITLE
Structure optimization for GCEED part

### PR DESCRIPTION
**Pull request by tt-ims**
I modify structure optimization for GCEED part. The optimization program is based on Quasi-Newton method.

### CODE REVIEW

**Comment by uemoto1** [comment]
add to whitelist

**Comment by uemoto1** [comment]
Above is execution command to Jenkins. Please ignore it.

**Comment by tt-ims** [comment]
@uemoto1 san

Thank you for your quick response.

**Comment by mn2007** [comment]
I'll check this PR by next Monday.

**Comment by mn2007** [comment]
I used following input coordinates on FX10 12nodes,
<pre>
&atomic_coor
'C'    0.000000    0.000000    0.700000  1 y
'H'    0.000000    0.000000    1.800000  2 y
'C'    0.000000    0.000000   -0.700000  1 y
'H'    0.000000    0.000000   -1.800000  2 y
/
</pre>
and obtained following output.
<pre>
 Quasi-Newton Optimization Step =  7
 atomic coordinate
C        0.00000023      0.00000022      0.59935294  1  y
H        0.00000009      0.00000006      1.67725174  2  y
C        0.00000025      0.00000039     -0.59935298  1  y
H        0.00000007      0.00000009     -1.67725178  2  y
 Optimization Converged
</pre>
It seems to work fine, so I merge this PR.

**Review by mn2007 — APPROVED** [review]
I approve this PR.

**Comment by tt-ims** [comment]
Thank you for merging, @mn2007 san.

**Pull request merged**
