### PR TITLE
implementation of domain parallel version for periodic boundary condition

### PR DESCRIPTION
**Pull request by mn2007**
As discussed this February, I implement domain parallel version for periodic boundary condition. Since there are many modifications, I set one week at least for the period of a review. 

There is a difference between an ARTED result and a GCEED result. I guess that the reason will become clear through the process of the unification. 
si

### CODE REVIEW

**Comment by mn2007** [comment]
I forgot to say one thing. Sample files are in testsuite directories.

**Comment by mn2007** [comment]
It seems that regression tests take long time. So I prepare substitutes.

**Comment by mn2007** [comment]
It seems that the regression tests still take long time. I'll modify the testsuites tomorrow.

**Comment by uemoto1** [comment]
Thank you @mn2007 san for developing!

In connection with the regression test, since the maintanance/migration of the jenkins server, presently we can not use SSL in the test result page. If you (and reviewers) want to access it, please use "http" address instead of the usual:
http://diana.ccs.tsukuba.ac.jp/jenkins/job/SALMON_PR_KNL01/

Sorry for the inconvenience.

**Comment by uemoto1** [comment]
Accordings to the regression test, I guess this code is almost working but its test sequence consts too much time (longer than the present limitation: 120min). 
At the end of the computation time, the test sequence is on `testsuites/113_bulk_Si_rt_pulse_dp` and calculating around:
```
     887    3.43287450  0.90767468E-12 -0.77344456E-12 -0.30392266E-04    31.99999992     -861.45179002
     888    3.43674470  0.83448431E-12 -0.68579779E-12 -0.28634239E-04    31.99999992     -861.45142428
     889    3.44061491  0.72894454E-12 -0.59879020E-12 -0.26869775E-04    31.99999992     -861.45107653
     890    3.44448512  0.59346459E-12 -0.51078039E-12 -0.25098945E-04    31.99999992     -861.45074690
```

Thius, what we need is (i) increase the time limitation of the test sequence or (ii) reduce the weight of the test job...

**Comment by mn2007** [comment]
Thank you for the comment, @uemoto1 san. By modifying CMakelist in testsuite, I tried to skip testsuites no. 112 and no. 113 which take long time, and to make run testsuites no. 114 and no. 115. But it didn't work. I'll try another solution.

**Comment by mn2007** [comment]
I found that there was a mistake in the program which checks number of division of proccesses. That part was in src/GCEED/common/check_numcpu.f90. So I'll modify.

**Comment by mn2007** [comment]
It seems that results for optical response caulcations in FX10 and Xeon Phi are different. I'll investigate the reason. I guess it takes long time.

**Comment by mn2007** [comment]
Calculations seem to successfully finish. @tt-ims san, could you check this PR? Even if there is no problem for this PR, could wait to merge until next Monday? Thanks in advance.

**Comment by tt-ims** [comment]
@mn2007 san,

OK. I will check this PR and wait to merge until next Monday.

**Comment by tt-ims** [comment]
@mn2007 san,

I checked your pull request. Except the problem that you indicated as the difference between an ARTED and GCEED results, There is no problem to merge this pull request.

**Comment by mn2007** [comment]
Thank you for merging, @tt-ims san.

**Pull request merged**
