### PR TITLE
Unified the namelists, atomic_spiecies in ARTED and group_atom in GCEED.

### PR DESCRIPTION
**Pull request by shunsuke-sato**
**Please merge this PR!**

To achieve common input, I unified the two namelists; `atomic_spiecies` in ARTED and `group_atom` in GCEED.

For GCEED part, the modification is small:
I renamed the input variables of `Mlps` and `Lref` to `Lmax_ps` and `Lloc_ps`, respectively. After reading these variables in the code, they are immediately substituted to original variables.
I would like to ask GCEED developers to accept this small change to avoid a variable confliction in ARTED. 

For ARTED part, the modification is NOT small:
- The name of the namelist; `&atomic_spiecies`, was changed to `&group_atom`. 
- Input variables of `NI` and `NE` in `&system`, and `ps_format` in `&pseudo` were moved in `&group_atom`.
- Furthermore, `NI` and `NE` were renamed to `MI` and `MKI` in order to fit GCEED format.
- Now the maximum angular momentum of projectors `Lmax_ps` can be controlled from input, as GCEED does
- Now different pseudopotential formats `ps_format` can be used for different species, as GCEED does.

**A Problem of input for pseudopotential format**
The pseudopotential format is described as a character expression, e.g. 'KY' and 'ABINIT', in ARTED input, while that is described by an integer in GCEED input.
Now I implemented the codes so that either expression can work for input for either code. However, this would be confusing for users. So, I would say we should choose one of them.

### CODE REVIEW

**Comment by shunsuke-sato** [comment]
@uemoto1 san, could you copy the error log of the build?
On my environment, this patch works well.

**Comment by uemoto1** [comment]
The error log is attached as below:

    [ 92%] Building Fortran object GCEED/CMakeFiles/gceed.dir/common/calc_gradient_fast_c.f90.o
    Linking Fortran static library libgceed.a
    [ 96%] Built target gceed
    [ 97%] Built target core
    Scanning dependencies of target salmon.mic
    [ 97%] Building Fortran object CMakeFiles/salmon.mic.dir/main/main.f90.o
    Linking Fortran executable ../salmon.mic
    ifort: コマンドライン・リマーク #10148: オプション '-i_dynamic' はサポートされていません。
    ARTED/control/libcontrol.a(control_sc.f90.o): 関数 `control_sc_mp_read_data_' 内:
    control_sc.f90:(.text+0xfbbe): `global_variables_mp_ps_format_' に対する定義されていない参照です
    ARTED/control/libcontrol.a(control_ms.f90.o): 関数 `control_ms_mp_read_data_' 内:
    control_ms.f90:(.text+0x10727): `global_variables_mp_ps_format_' に対する定義されていない参照です
    make[2]: *** [../salmon.mic] エラー 1
    make[1]: *** [CMakeFiles/salmon.mic.dir/all] エラー 2
    make: *** [all] エラー 2
    Build step 'シェルの実行' marked build as failure
    Setting status of 8bba99ddcb7bbcae923098e4d01e08cdebba923a to FAILURE with url https://diana.ccs.tsukuba.ac.jp/jenkins/job/SALMON_PULL_REQUEST/46/ and message: 'Build is failure.
     '
    Finished: FAILURE

**Comment by uemoto1** [comment]
The test above is performed by `configure.py --arch=intel-knl` with CMake builds.

**Comment by shunsuke-sato** [comment]
@uemoto1 san, thank you for the information. Then, I'll try to fix it later.

**Comment by shunsuke-sato** [comment]
@uemoto1 san, and @mn2007 san, I would like to ask you again to review this PR, although the structure of input for atom data is under discussion because this patch is not a proposal for input structure but an extension of ARTED's function to unify the input.

**Comment by mn2007** [comment]
As for GCEED part, there is no problem. Could @uemoto1 san merge if there is no problem in ARTED part?

**Comment by shunsuke-sato** [comment]
@uemoto1 san, could you copy the error message again, please? Thanks in advance.

**Comment by uemoto1** [comment]
The error logs below seems to be problem of the link dependencies of Make/CMakeLists.

    [ 97%] Built target core
    Linking Fortran executable ../salmon.mic
    ifort: コマンドライン・リマーク #10148: オプション '-i_dynamic' はサポートされていません。
    GCEED/rt/libgceed_rt.a(real_time_dft.f90.o): 関数 `real_time_dft_' 内:
    real_time_dft.f90:(.text+0x13e8): `scf_data_mp_mi_' に対する定義されていない参照です
    real_time_dft.f90:(.text+0xf5f8): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/rt/libgceed_rt.a(real_time_dft.f90.o): 関数 `time_evolution_' 内:
    real_time_dft.f90:(.text+0x2e0f7): `scf_data_mp_mi_' に対する定義されていない参照です
    real_time_dft.f90:(.text+0x2e106): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/rt/libgceed_rt.a(time_evolution_step.f90.o): 関数 `time_evolution_step_' 内:
    time_evolution_step.f90:(.text+0x8c21): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/rt/libgceed_rt.a(time_evolution_step.f90.o):time_evolution_step.f90:(.text+0x9aae): `scf_data_mp_mi_' に対する定義されていない参照がさらに続いています
    GCEED/scf/libgceed_scf.a(real_space_dft.f90.o): 関数 `real_space_dft_' 内:
    real_space_dft.f90:(.text+0x5bf5): `scf_data_mp_mki_' に対する定義されていない参照です
    real_space_dft.f90:(.text+0x5c52): `scf_data_mp_izatom_' に対する定義されていない参照です
    real_space_dft.f90:(.text+0x77d7): `scf_data_mp_mi_' に対する定義されていない参照です
    real_space_dft.f90:(.text+0xa9ca): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/scf/libgceed_scf.a(structure_opt.f90.o): 関数 `structure_opt_' 内:
    structure_opt.f90:(.text+0x3): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/scf/libgceed_scf.a(calc_pdos.f90.o): 関数 `calc_pdos_' 内:
    calc_pdos.f90:(.text+0x20): `scf_data_mp_mi_' に対する定義されていない参照です
    calc_pdos.f90:(.text+0x25b): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/scf/libgceed_scf.a(calc_pdos.f90.o):calc_pdos.f90:(.text+0x883): `scf_data_mp_mi_' に対する定義されていない参照がさらに続いています
    GCEED/common/libgceed_common.a(OUT_IN_data.f90.o): 関数 `out_data_' 内:
    OUT_IN_data.f90:(.text+0x9a9a): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x9ab9): `scf_data_mp_izatom_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x9b1b): `scf_data_mp_ipsfileform_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x9d86): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0xa3e4): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0xa593): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0xa5d4): `scf_data_mp_mki_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(OUT_IN_data.f90.o): 関数 `in_data_' 内:
    OUT_IN_data.f90:(.text+0x12c0c): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x138a2): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1390b): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x17ed7): `scf_data_mp_mki_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(OUT_IN_data.f90.o):OUT_IN_data.f90:(.text+0x17efe): `scf_data_mp_mki_' に対する定義されていない参照がさらに続いています
    GCEED/common/libgceed_common.a(OUT_IN_data.f90.o): 関数 `in_data_' 内:
    OUT_IN_data.f90:(.text+0x1a9cf): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b369): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b3e5): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b5cd): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b5f5): `scf_data_mp_izatom_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b63f): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b667): `scf_data_mp_ipsfileform_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b6aa): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b6d4): `scf_data_mp_ipsfileform_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b6f7): `scf_data_mp_ipsfileform_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b8d0): `scf_data_mp_izatom_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b8d5): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b8f7): `scf_data_mp_ipsfileform_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b8fc): `scf_data_mp_mki_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1b9ee): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1baaa): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1bb89): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1bc3e): `scf_data_mp_mi_' に対する定義されていない参照です
    OUT_IN_data.f90:(.text+0x1bd60): `scf_data_mp_mki_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(storevpp.f90.o): 関数 `storevpp_' 内:
    storevpp.f90:(.text+0x12): `scf_data_mp_mki_' に対する定義されていない参照です
    storevpp.f90:(.text+0x44a): `scf_data_mp_ipsfileform_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(calcJxyz2nd.f90.o): 関数 `calcjxyz2nd_' 内:
    calcJxyz2nd.f90:(.text+0x418): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(calcJxyz.f90.o): 関数 `calcjxyz_' 内:
    calcJxyz.f90:(.text+0x27): `scf_data_mp_mi_' に対する定義されていない参照です
    calcJxyz.f90:(.text+0x7e3): `scf_data_mp_mi_' に対する定義されていない参照です
    calcJxyz.f90:(.text+0x146f): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(calcuV.f90.o): 関数 `calcuv_' 内:
    calcuV.f90:(.text+0x12): `scf_data_mp_mki_' に対する定義されていない参照です
    calcuV.f90:(.text+0x7bd): `scf_data_mp_mi_' に対する定義されていない参照です
    calcuV.f90:(.text+0x1477): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(calcVpsl.f90.o): 関数 `calcvpsl_' 内:
    calcVpsl.f90:(.text+0xda): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(hartree_boundary.f90.o): 関数 `hartree_boundary_' 内:
    hartree_boundary.f90:(.text+0x7004): `scf_data_mp_mi_' に対する定義されていない参照です
    hartree_boundary.f90:(.text+0x70e7): `scf_data_mp_mi_' に対する定義されていない参照です
    GCEED/common/libgceed_common.a(hartree_boundary.f90.o):hartree_boundary.f90:(.text+0x7197): `scf_data_mp_mi_' に対する定義されていない参照がさらに続いています
    make[2]: *** [../salmon.mic] エラー 1
    make[1]: *** [CMakeFiles/salmon.mic.dir/all] エラー 2
    make: *** [all] エラー 2
    Build step 'シェルの実行' marked build as failure
    Setting status of a6ef8fb17e4fbc2e910537171fd7581df38e6d4a to FAILURE with url https://diana.ccs.tsukuba.ac.jp/jenkins/job/SALMON_PULL_REQUEST/59/ and message: 'Build is failure.
     '
    Finished: FAILURE

**Comment by uemoto1** [comment]
test this please

**Pull request merged**
