### PR TITLE
Make a slight modification to classic em

### PR DESCRIPTION
**Pull request by tt-ims**
This PR makes a slight modification to classic em calculation.
@mn2007 san, could you review this PR?

### CODE REVIEW

**Comment by mn2007** [comment]
I understand, @tt-ims san. I'll check.

**Comment by tt-ims** [comment]
@mn2007 san, Thank you.

**Comment by mn2007** [comment]
Calculated results obtained on FX100 are same as previous. So I merge this PR. Thank you, @tt-ims san.

**Comment by tt-ims** [comment]
Thank you for merging, @mn2007 san!

**Pull request merged**
