### PR TITLE
add lorentzian function for DOS and PDOS

### PR DESCRIPTION
**Pull request by mn2007**
Sorry, @uemoto1 san. I need lorentzian function for DOS and PDOS in the GCEED part immediately. So I implement that function to the GCEED part. I checked that calculations for the ARTED part and the GCEED part successfully finished. 

I'd like @uemoto1 san to check this function because you implemented this function to the ARTED part. Could you please check? Since today is holiday, there is no problem if the check is not done today.

### CODE REVIEW

**Comment by uemoto1** [comment]
Thank you for implementation.

This PR is very helpful for compatibility. 
I confirmed the choices of `lorentzian` and `gaussian` reproduces the similar results without any significant differences.

For future work, I recommend modifying the header of output files to indicate the unit system correctly and fix the documentation to enables `0d` mode of `out_dos_????` when we have time enough.

However, I think the points above are not major problems, and guess this PR is possible to merge.

**Comment by mn2007** [comment]
Thank you for merging, @uemoto1 san. I may do the modification suggested by you as for future work.

**Comment by mn2007** [comment]
@uemoto1 san, I guess e-mail will be delivered to you by adding comment in this place. So can I confirm what you said? I think unit system is written in header of output dos and pdos files generated in the GCEED part in current situation, and there is no need to modificate. And only I (or we?) have to do is modifying the developer's manual. Is that correct?

**Comment by uemoto1** [comment]
@mn2007 san, I have checked the related part for PR#123, and  I also found the previous recommendation is my misunderstanding. The current implementation, the  file header works well.
I agree there is no necessary to modify the header section.

**Comment by mn2007** [comment]
Thank you for your reply. If PR#124 is merged, I will add same function as PR#124 and modify the manual.

**Comment by uemoto1** [comment]
Thanks!

**Pull request merged**
