### PR TITLE
Introduced atomic reduced coordinates, Rion_red.

### PR DESCRIPTION
**Pull request by shunsuke-sato**
To prevent overwriting the input variable, `Rion(3,natom)`, I introduced the atomic reduced coordinates `Rion_red(3,natom)`.

### CODE REVIEW

**Comment by mn2007** [comment]
Amazing. It actually runs without any modification for the GCEED part nor GCEED inputs.  That's no problem for me.

**Comment by shunsuke-sato** [comment]
@mn2007 thank you for reviewing! I would say that still we need atomic coordinates or its file in input for RT mode of GCEED. But, if I understand correctly, it is not needed originally. So, please modify the code accordingly if you need.

**Comment by mn2007** [comment]
I understand. But we don't care if atomic coordinates are wrtitten in the input file for the RT mode. Thank you for your comment.

**Comment by mn2007** [comment]
I cannot merge because this modification is done to ARTED part. I'd like to ask other people to review and merge this PR.

**Comment by uemoto1** [comment]
Thanks Sato-san, I have checked this PR.

**Comment by yhirokawa-ccs** [comment]
Unfortunately, this PR arose deadlock in latest codes at GCEED part (commit ID: 835a6b7).

I executed it with C2H2 sample under knights landing 12nodes, but it froze before calling init_mesh() subroutine. By reverting this PR, I made sure that a deadlock is solved.
Would you please check the latest codes?

**Comment by shunsuke-sato** [comment]
@yhirokawa san, thank you for reporting that! I'll check it! In the test, do you use `C2H2_gs.inp`?

**Comment by shunsuke-sato** [comment]
I found a bug in my implementation! I'll fix it and send a PR soon.

**Comment by yhirokawa-ccs** [comment]
@shunsuke-sato san, thank you for quick response. Yes, I used a C2H2_gs.inp

**Pull request merged**
