### PR TITLE
Fixed a compile error under GCC.

### PR DESCRIPTION
**Pull request by yhirokawa-ccs**
hpsi.f90 wraps to module.

Environment:
+ GCC 4.8.5
+ RHEL 7.3
+ Intel libraries 2017

### CODE REVIEW

**Comment by uemoto1** [comment]
Hirokawa-san, Thank you for contribution.
I have checked I can successfully build this PR by using __gcc 4.8.5 on OFP__.

**Comment by uemoto1** [comment]
I paste Jenkins's error log as below:

    -- Build files have been written to: /var/lib/jenkins/workspace/SALMON_PULL_REQUEST/build
        $  cmake  -D CMAKE_TOOLCHAIN_FILE=intel-knl -D CMAKE_BUILD_TYPE=Release -D CMAKE_VERBOSE_MAKEFILE=off ..
    [  1%] Built target core
    [  7%] Built target modules
    [ 10%] Built target preparation
    [ 11%] Building Fortran object ARTED/GS/CMakeFiles/GS.dir/diag.f90.o
    /var/lib/jenkins/workspace/SALMON_PULL_REQUEST/ARTED/GS/diag.f90(26): エラー #7002: コンパイル済みモジュールファイルを開くときのエラーです。INCLUDE パスを確認してください。   [HPSI]
      use hpsi, only: hpsi_omp_KB_GS
    ------^
    /var/lib/jenkins/workspace/SALMON_PULL_REQUEST/ARTED/GS/diag.f90(67): エラー #6406: 属性が矛盾しているか名前が複数回宣言されています。   [HPSI_OMP_KB_GS]
          call hpsi_omp_KB_GS(ik,tpsi_omp(:,thr_id),ttpsi_omp(:,thr_id),htpsi_omp(:,thr_id))
    -----------^
    /var/lib/jenkins/workspace/SALMON_PULL_REQUEST/ARTED/GS/diag.f90(26): エラー #6580: 参照限定リストの名前が存在しません。   [HPSI_OMP_KB_GS]
      use hpsi, only: hpsi_omp_KB_GS
    ------------------^
    コンパイルは /var/lib/jenkins/workspace/SALMON_PULL_REQUEST/ARTED/GS/diag.f90 で異常終了しました (コード 1)。
    make[2]: *** [ARTED/GS/CMakeFiles/GS.dir/diag.f90.o] エラー 1
    make[1]: *** [ARTED/GS/CMakeFiles/GS.dir/all] エラー 2
    make: *** [all] エラー 2

**Comment by yhirokawa-ccs** [comment]
@uemoto1 san, thank you for comments.
I fixed a compile error under Intel compiler.

**Comment by uemoto1** [comment]
Thank you! I confirm the fixed version works well.

**Comment by shunsuke-sato** [comment]
@yhirokawa san, thank you for proving hpsi module! I have tested it and will approve this PR.
@uemoto1 san, this time, I'll merge it since I expect you would be ultra busy. But, if you think a PR is fine, please feel free to merge it!

**Pull request merged**
