### PR TITLE
fix: update gnu makefiles

### PR DESCRIPTION
**Pull request by uemoto1**
Update GNU Makefile to follow up present source structure.

### CODE REVIEW

**Comment by mn2007** [comment]
Thank you, @uemoto1 san. I'll check.

**Comment by mn2007** [comment]
I confirmed gs calculation for a C2H2 molecule successfully finished on FX100. So I merge.

**Review by mn2007 — APPROVED** [review]
I approve this PR.

**Comment by uemoto1** [comment]
Thank you @mn2007 san for quick checking!

**Pull request merged**
