### PR TITLE
implement FFTE

### PR DESCRIPTION
**Pull request by mn2007**
I implement FFTE.

### CODE REVIEW

**Comment by mn2007** [comment]
I'm not sure why the check on knl is not successful. I'll investigate tomorrow.

**Comment by mn2007** [comment]
All checks seem to have passed successfully. @tt-ims san, could you check?

**Comment by tt-ims** [comment]
I will check this PR soon.

**Comment by tt-ims** [comment]
I approve this PR.

**Comment by mn2007** [comment]
Thank you for merging, @tt-ims san.

**Pull request merged**
