### PR TITLE
add function of temperature in the GCEED part

### PR DESCRIPTION
**Pull request by mn2007**
This PR enables to treat temperature in the GCEED part. To use function of temperature, please modify input files as follows. 
<pre>
&system
  iperiodic = 0
  al = 16d0, 16d0, 16d0
-  nstate = 5
+  nstate = 10
  nelem = 2
  natom = 4
  nelec = 10
+  temperature_k = 300.d0
/
</pre>

@tt-ims san, could you check this PR?

### CODE REVIEW

**Comment by mn2007** [comment]
test this please

**Comment by tt-ims** [comment]
@mn2007 san, ok, I will check it soon.

**Comment by tt-ims** [comment]
I confirmed that the finite-temperature option works. I approve this PR.

**Comment by mn2007** [comment]
Thank you for merging, @tt-ims san.

**Pull request merged**
