### PR TITLE
Restart from backup

### PR DESCRIPTION
**Pull request by shunsuke-sato**
For ARTED part, I reconstructed the backup function, which was broken in the merging process.
Now, one can restart the single-cell/multi-scale calculation from backup.

### CODE REVIEW

**Comment by uemoto1** [comment]
Thank you for developing @shunsuke-sato san.
I have checked successful build of this code and no difference in the output file.

However, I need a help to test the restarting from the checkpoint file (`SYSNAME_re_??????.out`).
I found it is very difficult to execute the job from a checkpoint , and have not succeeded to restarting in the current version SALMON.
I think I have to grasp the restarting method in order to create the tutorial. Please let me know how to use it ...

**Comment by shunsuke-sato** [comment]
@uemoto1 san, thank you for reviewing. The way to use the restart is same as that of ARTED. Just use the file of `SYSNAME_re_??????.out` as stdin. What kind of error do you get?

**Comment by uemoto1** [comment]
Thx @shunsuke-sato san, I retried it again.

I modified `ARTED/data/input_sc_Si.inp` to enable backup frequency;
https://gist.github.com/uemoto1/5f9659933f284d842786de2da7a8801a
And I prepared the checkpoint file at n=1500;
https://gist.github.com/uemoto1/2aaebb176c4cfb7c105fa963ec792ddc

Now, we have the error message as below:
```
Error in input: The following inputs are incompatible.
file_atom_coor, file_atom_red_coor, &atomic_coor, and &atomic_red_coor.
```

**Comment by shunsuke-sato** [comment]
@uemoto1 san, let me ask a question. What is this file?
https://gist.github.com/uemoto1/2aaebb176c4cfb7c105fa963ec792ddc
Is this created by SALMON of this branch as an output of restart? Or, you mean you prepared it by yourself?

**Comment by shunsuke-sato** [comment]
Just, let me add something. If you properly run the code, you would get something like following as an restart input
```
&control
restart_option = 'restart'  
Time_shutdown=  -0.1000000000000000E+001
directory = './'  !directory
dump_filename = 'dump_Si_003000'  !dump_filename
/
&tgrid
Nt =    4000  ! Nt: If you want continuous execution, please change the value.
/
&system
iperiodic = 3
/
```

**Comment by shunsuke-sato** [comment]
Sorry for scattered comments. Potentially, you might run SALMON on another branch rather than this branch since in this patch I completely quit to use `reentrance`, and start to use `restart` instead.

**Comment by uemoto1** [comment]
Thank you @shunsuke-sato san.
It seems to be very easy mistake.
I will try it again.

**Comment by uemoto1** [comment]
Okey, @shunsuke-sato san, I found I have used the old binary (which prepared for comparison) by mistake. Now, I successfully executed from the checkpoint, and it works well! I think it is okey to merge.

Thank you for the rapid answer to my question, and this is so helpful!

**Pull request merged**
