### PR TITLE
Optimization of hartree calculation in GCEED part.

### PR DESCRIPTION
**Pull request by yhirokawa-ccs**
I optimized the following source files:

+ GCEED/common/hartree_cg.f90
+ GCEED/common/hartree_boundary.f90
+ GCEED/common/laplacianf.h

This PR reduces computation time, especially when hartree calculation (CG method) consumes a lot of computational costs.

It changes tendency of computational error because computation order is changed by modifying OpenMP parallelization manner (e.g. `omp collapse` clause).
Unfortunately, GCEED part does not provide automatic test case yet, so I can not validate the calculation results.

@mn2007 san, would you please let me check the calculation results with it?

### CODE REVIEW

**Comment by mn2007** [comment]
Thank you for implementing, @yhirokawa san. I'll check later.

**Comment by mn2007** [comment]
@yhirokawa san, maybe I'll do this work tomorrow morning. By the way, could you tell me the meaning of [WIP]? And can I merge if there is no problem with this PR?

**Comment by mn2007** [comment]
The build succeeds on OFP, while it fails on FX10. I cannot figure out how to solve. I'll continue to try to fix, but could you tell me if you know something? Followings are error messages. 

<pre>
[ 48%] Building Fortran object src/GCEED/common/CMakeFiles/gceed_rtl_common.dir/hartree_boundary.f90.o
Fortran diagnostic messages: program name(Hartree_boundary)
  jwd1800i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: OpenMP continuation directive line must follow after the OpenMP continued directive line.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'rholm3' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'LL' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'lm' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'ixbox' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'iybox' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'izbox' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'xx' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'yy' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'zz' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'rr' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'rinv' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'xxxx' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'yyyy' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'zzzz' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'Ylm' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd1302i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 232: Not a valid Fortran statement.
  jwd1800i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: OpenMP continuation directive line must follow after the OpenMP continued directive line.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'Hvol' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'trho' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'rholm3' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'lmax_meo' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'pl' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'center_trho' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'gridcoo' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'ii' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'icorr_xyz_pole' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 236: Data-sharing attribute clause of the variable 'cl' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd1302i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 237: Not a valid Fortran statement.
make[2]: *** [src/GCEED/common/CMakeFiles/gceed_rtl_common.dir/hartree_boundary.f90.o] Error 1
make[1]: *** [src/GCEED/common/CMakeFiles/gceed_rtl_common.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by yhirokawa-ccs** [comment]
@mn2007 san, thank you for testing under FX10, and I apologize that it caused OpenMP syntax error. Also, I forgot that removes "WIP" from title. I fixed these.
Would you please recheck a branch?

**Comment by mn2007** [comment]
@yhirokawa san, thank you for modifying. But the build still fails. I write new error messages. Sorry for my few contribution. 
<pre>
[ 48%] Building Fortran object src/GCEED/common/CMakeFiles/gceed_rtl_common.dir/hartree_boundary.f90.o
Fortran diagnostic messages: program name(Hartree_boundary)
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'LL' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'lm' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'ixbox' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'iybox' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'izbox' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'xx' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'yy' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'zz' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'rr' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'rinv' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'xxxx' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'yyyy' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'zzzz' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'Ylm' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'ii' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'pl' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'cl' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'lmax_meo' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
  jwd2805i-s  "/k/home/users/sr9/SALMON/SALMON-170914-0940-hirokawa-hartree/SALMON-noda/src/GCEED/common/hartree_boundary.f90", line 231: Data-sharing attribute clause of the variable 'Hvol' used in the lexical extent of the parallel region must be specified when DEFAULT(NONE) is specified.
make[2]: *** [src/GCEED/common/CMakeFiles/gceed_rtl_common.dir/hartree_boundary.f90.o] Error 1
make[1]: *** [src/GCEED/common/CMakeFiles/gceed_rtl_common.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by yhirokawa-ccs** [comment]
@mn2007 san, thank you for reporting. 
Probably, I understood problem and fixed a compile error you reported.
Would you please check again?

**Comment by mn2007** [comment]
Thank you for fixing the problem, @yhirokawa san! The build passed. Now I check performance. Please wait for a while.

**Comment by mn2007** [comment]
I checked the performance for the impluse calculation for the GCEED part. By @yhirokawa san's  modification, total elapsed times change from `144.70` sec to `146.15` sec on the FX10 12nodes, and from `82.56` sec to `70.85` sec on the OFP 12 nodes. Since 17% increase for the performance on the OFP has been seen, I merge this PR. Thanks a lot, @yhirokawa san!

**Review by mn2007 — APPROVED** [review]
I approve this PR.

**Comment by mn2007** [comment]
I modify my reports. The number of nodes I used on the OFP was not 12 but 8. Total elapsed times are what I gave above. Sorry for confusing.

**Comment by yhirokawa-ccs** [comment]
Thank you for reporting and merging, @mn2007 san.
FX10 performance decreased (or it didn't work) is surprisingly result for me.

**Pull request merged**
