### PR TITLE
move namelist from GCEED to SALMON/module

### PR DESCRIPTION
**Pull request by mn2007**
I move namelist from GCEED to SALMON/module. 

I had mistaken some unit conversion which I prepared in inputoutput.f90. There was no problem to use them if one uses eV/A/fs, but it may cause some problems when one uses a.u. in the future. So I fix it. In addition, I add comma to reduce warning in writing input variables for Lloc_ps, iZatom.  

I confirmed that it runs successfully for ARTED and GCEED parts. Could someone merge this PR?

### CODE REVIEW

**Comment by uemoto1** [comment]
Thank you, @mn2007 san. I will check it later...

**Comment by uemoto1** [comment]
@mn2007 san. Thank you for merging PR#109.
I suspect, due to PR#109, this PR occurs the confliction to develop branch. Check it, please.

**Comment by mn2007** [comment]
@uemoto1 san, thank you for suggesting. I'll resolve the conflict, so please wait until it is resolved.

**Comment by mn2007** [comment]
I resolved the conflict. Could you continue to check?

**Comment by uemoto1** [comment]
Okey, I will continue the reviewing, Please wait a moment...

**Comment by uemoto1** [comment]
Thank you @mn2007 san for implementation, and sorry for late reply.

I have grasped your modification which replaces the original "read_input_(scf|rt)" to new "convert_input_(scr|rt)" subroutine section, and moves "the GCEED's build-in namelist loader" to the salmon_global and inputoutput module. At the same time, some native groups such as "group fundamental" is completely removed from the source code.

I confirmed the isolated mode calculation (GCEED) still works and reproduces the previous calculation results, and I think it is okey to merge to the development branch.

**Comment by mn2007** [comment]
I'm so glad to be merged. Thank you, @uemoto1 san.

**Pull request merged**
