### PR TITLE
use underline for filename

### PR DESCRIPTION
**Pull request by mn2007**
I use underline for filename in the GCEED part to follow the ARTED part. Since I didn't succeed to display the total energy at `t=0` correctly, I give up to display a line of `t=0`. @uemoto1 san, could you check this PR?

### CODE REVIEW

**Comment by mn2007** [comment]
I found that I forgot to modify the script for regression test. I'll modify it.

**Comment by mn2007** [comment]
All checks seems to have passed. @uemoto1 san, could you check?

**Comment by uemoto1** [comment]
Thank you @mn2007 san, I will check it this night.

**Comment by mn2007** [comment]
Thanks a lot, @uemoto1 san.

**Review by uemoto1 — APPROVED** [review]
Okay, I confirmed the filename is successfully changed! Thank you for contribution!

**Comment by mn2007** [comment]
Thank you for checking and merging, @uemoto1 san.

**Pull request merged**
