### PR TITLE
Fix GNU Makefiles for the new directory structure

### PR DESCRIPTION
**Pull request by uemoto1**
## About This Pull Request
This pull request contains the GNU makefiles for the modified directory structure in PR#144. Here some kinds of platform-specific makefiles `makefiles/Makefile.arch` are provided as below:

- Makefile.fujitsu
- Makefile.intel
- Makefile.intel-avx2
- Makefile.intel-knl
- Makefile.gnu
- Makefile.intel-avx
- Makefile.intel-knc

## How to build SALMON by GNU Make
The building method is a bit changed after merging PR#143:

1. Enter to the top of the source tree:
```
$ cd SALMON
```

2. Execute `make` command with using the platform-specific makefile:
```
$ make -f makefiles/Makefile.ARCH
```

### Uninstallation
To remove the compiled binary and temporary files, execute:
```
$ make clean -f makefiles/Makefile.ARCH 
```

### CODE REVIEW

**Comment by uemoto1** [comment]
I fix the makefile problem which occurred by the recent PRs, and checked for the intel platform.
If anyone can test it for fujitsu environment. please test it.

**Comment by mn2007** [comment]
Thank you for creating Makefiles, @uemoto1 san. I checked with fujitsu environment by the way which @shunsuke-sato san teached me. So this test is done by merged program. When I didn't create the build_temp directory, following error as follows appeared and build stopped
<pre>
cp src/versionf.h.in build_temp/versionf.h
cp: cannot create regular file `build_temp/versionf.h': No such file or directory
make: *** [build_temp/versionf.h] Error 1
</pre>
I think we need to write the disciption of making build_temp to somewhere. Anyway, after I created the build_temp directory, the build kept going. but it stopped with omitting following error massage. 
<pre>
mpifrtpx -O3 -Kfast,openmp,simd=1 -Cpp -Kocl,nooptmsg -M build_temp -o build_temp/src/main.o -c src/main.f90 -I build_temp
Fortran diagnostic messages: program name(main)
 Internal subprogram name(print_software_version)
  jwd1035i-s  "build_temp/versionf.h", line 1, column 46: Invalid operator.
  jwd1006i-s  "build_temp/versionf.h", line 1, column 47: Character not allowed by syntax rules or not a valid Fortran character.
  jwd1006i-s  "build_temp/versionf.h", line 1, column 57: Character not allowed by syntax rules or not a valid Fortran character.
  jwd2005i-w  "src/main.f90", line 32: 'GIT_FOUND' is used but never set.
make: *** [build_temp/src/main.o] Error 1
</pre>
This error also occured in intel-avx2 environment. Could you fix this? Or could you tell me how to solve?

**Comment by mn2007** [comment]
Thank you for fixing. I'll check later. But I may not check this as soon as possible. Sorry for inconvenience.

**Comment by uemoto1** [comment]
Thank you for checking @mn2007 san.
I confirmed a problem originating from the interaction with PR#154 which I merged after pushing this PR. (I found `versionf.h` related error is a bit complicated... My bugfix seems to be not best solution, but I will works in present environments)

I'm not hurry because of the holidays...
Please someone check how the makefile works in your platform, when you have time enough.

**Comment by mn2007** [comment]
I confirmed that build_temp is automatically generated and the build finished successfully on intel and FX10 environment. And calculations finished successfully as usual. So I merge this PR. Thank you, @uemoto1 san.

**Pull request merged**
