### PR TITLE
Add common output files for RT calculation

### PR DESCRIPTION
**Pull request by uemoto1**
## About This Pull Request

This modification provides the subroutines of the common output file format for SALMON-TDDFT. 
In the previous PR (https://github.com/SALMON-TDDFT/SALMON/pull/136), the output for GS calculation is proposed.
This PR experimentally implements the output for **RT calculation**. 
I employ the file formats discussed on **SALMON June meeting**:
https://www.dropbox.com/s/43qyhxj0n5y7a5z/uemoto0805_output_format.pdf?dl=0

- Add the `SYSName_rt.data`
- Modify the fileheader of output files
- Modify the file header of `SYSName_k.data` and `SYSName_eigen.data`
- Move the defination of global variable `file_(k|eigen|rt)_data` to initialization subroutine and enables its backup
- Use reduced coordinate system for k-points

The ordinary output files (e.g. `SYSName_j_ac.out` ...) have also remained for now to keep the compatibility of the old calculation results.

### RT outputs (proposed in this PR)

- `SYSName_rt.data` : describe the k-point coordinates (only in 3d mode)

| Column | Detail | Unit |
|----------|------------|------|
| 1 | t | Time |
| 2:4 | E | Electric field  |
| 5:7 | J | (Matter) Current Density |
| 7:9 | eA/c | Vector Potential Field |

```
# J   : Matter current density
# E   : Total Electric Field
# eAc : Total Vector-potential
# Time [a.u.]  Ex [a.u.]  Ey [a.u.]  Ez [a.u.]  Jx [a.u.]  Jy [a.u.]  Jz [a.u.] eAcx [a.u.] eAcy [a.u.] eAcz [a.u.]
.........
```

### GS outputs (proposed in previous PR)

- `SYSName_k.data` : describe the k-point coordinates (only in 3d mode)

| Column | Detail | Unit |
|----------|------------|------|
| 1 | k-point index | integer starts from 1 |
| 2:4 | kx, ky, kz (reduced) oordinates | dimensionless |
| 5 | k-point weights | dimensionless |

```
# ik           : k-point index
# (kx, ky, kz) : Reduced coordinate of k-point
# kw           : Weight of k-point
# ik kx ky kz kw
.........
```

- `SYSName_eigen.data` : describe the eigenenergies and occupation number

| Column | Detail | Unit |
|----------|------------|------|
| 1 | k-point index | integer starts from 1  |
| 2 | band index | integer starts from 1  |
| 3 | eigenenergy  | energy |
| 4 | occupation | dimensionless |

```
# ik           : k-point index
# ib           : band index
# energy       : electron eigenenergy
# occup        : electron occupation
# ik kx energy [a.u.] occup
.........
```

## Future Work
- Add the similar output subroutines for GCEED section
- Add the common output formats of LR calculation

### CODE REVIEW

**Comment by mn2007** [comment]
After the automatic check pass, I'll review this PR.

**Comment by uemoto1** [comment]
test this please

**Comment by mn2007** [comment]
I'll check this later. Thank you, @uemoto1 san.

**Comment by mn2007** [comment]
I confirmed that current is not changed as before by this modification, and it seems that files are generated correctly. So I merge this PR.

**Pull request merged**
