### PR TITLE
unite Broyden subroutines

### PR DESCRIPTION
**Pull request by mn2007**
I unite Broyden subroutines implemented in the ARTED part and the GCEED part. 

Could you all wait until jenkins finishes checks? Thank you for your patience.

### CODE REVIEW

**Comment by mn2007** [comment]
Jenkins's test has successfully finished. So could you check this PR, @shunsuke-sato san? 

For other people, please do not hesitate to give comments to this PR.

**Comment by shunsuke-sato** [comment]
@mn2007 san, thank you for your implementation.
Yes, I can review this PR. But, I have something to do this weekend. So, probably, I can review in the next week.

**Review by shunsuke-sato — CHANGES_REQUESTED** [review]
@mn2007 san, thank you for your development. I tried to review, but I found a problem in compiling.
`src/GCEED/scf/buffer_broyden_ns.f90` does not have `implicit none` statement, and a couple of variables are not declared.
Could you fix the problem?

**Comment by mn2007** [comment]
Thank you for your comment, @shunsuke-sato san. I fixed the problem you pointed out. Could you continue to check this PR? I wait for the next comment.

**Comment by shunsuke-sato** [comment]
@mn2007 san, thank you for fixing the problem. I have confirmed that the patch reproduces the original results. Then, I merge it.

**Review by shunsuke-sato — APPROVED** [review]

**Comment by mn2007** [comment]
Thank you for merging, @shunsuke-sato san.

**Pull request merged**
